### ISSUE TITLE
V1+ Auto Unlock Mode RX Characteristic

### ISSUE THREAD

**Issue by baspeters** [Imaginous/Cowboy_Untamed#1]
As an IOS user I have a small question regarding enabling the Auto Unlock Mode for the V1+. Is it possible to share the RX Characteristic string to enable/disable this feature?

Thanks a lot for your great efforts, keep up the good work.

**Comment by Imaginous** [comment]
I have updated [IOS.md](https://github.com/Imaginous/Cowboy_Untamed/blob/main/IOS.md) to include the command to enable / disable Auto Unlock.

**Comment by baspeters** [comment]
Thank you very much, highly appreciated
