### ISSUE TITLE
Bluetooth conac

### ISSUE THREAD

**Issue by darnel007** [Imaginous/Cowboy_Untamed#15]
Bluetooth connection cannot be established on Android 12. I have a samsung z flip 3. Your suggested solution didn't work for me. I am thankful for any help.

**Comment by Imaginous** [comment]
Did you use the latest version?

Please check the app permissions manually and make sure bluetooth is allowed.

What message (toast) pops up?

**Comment by darnel007** [comment]
It works thanks 👍🏻 the permissions are missing

**Comment by Imaginous** [comment]
I will have a look at it why the permissions popup is not show.

It should ask for it.

But glad it's working.

**Comment by Imaginous** [comment]
You can give [beta version 3.34](https://github.com/Imaginous/Cowboy_Untamed/releases/download/V3.34/cowboyuntamed_v3_34.apk) a try.
