### ISSUE TITLE
Need android.permission bluetooth_connect

### ISSUE THREAD

**Issue by wayneLaw1** [Imaginous/Cowboy_Untamed#16]
Just bought a Samsun S22 using Android 12 and the app will not connect.  keep getting the error: need android.permission bluetooth_connect
Work find with Oppo which was Android 11

Is there any fix?

thanks
Wayne

**Comment by wayneLaw1** [comment]
Yer: You can go the apps and set the bluetooth permissions manually.

 

Worded thxs

**Comment by Imaginous** [comment]
I will have a look at it to see why the app didn't show the popup.

Enjoy Untamed

**Comment by Imaginous** [comment]
You can give [beta version 3.34](https://github.com/Imaginous/Cowboy_Untamed/releases/download/V3.34/cowboyuntamed_v3_34.apk) a try.

**Comment by wayneLaw1** [comment]
That seemed to work. But not sure if at all my fixing the issues prior to you new update affected it. This for the quick update  :-)Get Outlook for Android
