### ISSUE TITLE
No BT connection with Android 12 and Untamed v3.22

### ISSUE THREAD

**Issue by CBGTI** [Imaginous/Cowboy_Untamed#17]
My Poco F2 Pro just goes under Android 12 today, and it lost connection with my Cowboy V2 (just with Untamed).
Yesterday, under Android 11, it was OK.

I accepted all (the 4) permissions for Untamed v3.22.
I had the v3.22 since it was released. 
Cowboy App and Bronco work.

When I launch your app, I can just (shortly) see two small popup :  
- Need Android Permission Bluetooth
- No paired bike found

I also try to clear all datas of Untamed, but it doesn't change anything.   :-/

![messages_0](https://user-images.githubusercontent.com/89838333/165644542-dcee1815-e204-4a4f-b9d8-9e04c237db65.jpeg)
![messages_1](https://user-images.githubusercontent.com/89838333/165644546-7f455530-bbf2-48d8-bd13-2af005048ae2.jpeg)

**Comment by Imaginous** [comment]
I will have a look at it this weekend.
In the meantime go to apps and grant the bluetooth permission by hand. 

It should solve the problem for now. 

Still haven't got an Android 12 phone myself and bluetooth testing in the emulator is not really possible.

**Comment by Imaginous** [comment]
You can give [beta version 3.34](https://github.com/Imaginous/Cowboy_Untamed/releases/download/V3.34/cowboyuntamed_v3_34.apk) a try.

**Comment by CBGTI** [comment]
Awesome !
It work well this time!
Thanks for your hard work and your reactivity ! 

![messages_0](https://user-images.githubusercontent.com/89838333/165717853-122fd5f3-8509-4274-8d32-9f1dca5036bb.jpeg)
![messages_1](https://user-images.githubusercontent.com/89838333/165717856-8c871324-d509-43b8-913f-41090b10061a.jpeg)
![messages_2](https://user-images.githubusercontent.com/89838333/165717857-a6f7a671-36d5-4d18-84c9-342b6fe4dc7b.jpeg)
![messages_3](https://user-images.githubusercontent.com/89838333/165717859-e0d257d5-52a1-4c06-a845-267636bc1ed6.jpeg)

**Comment by CBGTI** [comment]
This time, when I launch this App, my phone asks me for BT autorisation.

**Comment by Imaginous** [comment]
Does it ask it every time or just once?

**Comment by CBGTI** [comment]
It just ask for the first time.

**Comment by CBGTI** [comment]
But in my phone, your App isn't listed as an App to activate BT.

**Comment by CBGTI** [comment]
It's my BT parameters (on Poco/Xiaomi/Redmi



![messages_5](https://user-images.githubusercontent.com/89838333/165720043-f819633f-6a42-4168-921b-34bf6be41f23.jpeg)
)

**Comment by CBGTI** [comment]
It's strange, but it works.  ;-)

**Comment by Imaginous** [comment]
I will have a look at that.
As far as I know I don't request it either.
I only check if it's enabled, but I don't enable it automatically or allow the addition of new bluetooth devices. They need to be paired.

I dive in the permissions once again... Google keeps on changing it ;)

**Comment by CBGTI** [comment]
In the Cowboy app per exemple, if the Bluetooth isn't activated, when we launch their App, it ask for BT activation.
Each time if BT is disabled.
It could be solve your "problem" definitively.   :-)

![messages_6](https://user-images.githubusercontent.com/89838333/165731050-16b256c6-1617-4815-9b12-459ea251ecc2.jpeg)

**Comment by Imaginous** [comment]
I close this item, I think everything is solved in the latest version.
