### ISSUE TITLE
Request to other Untamed C(3)owboys

### ISSUE THREAD

**Issue by OpenAai** [Imaginous/Cowboy_Untamed#19]
With my C3 I still have the judder issue, so I would like to ask other C3 owners their settings, with hopefully better results. I tried the settings, as advices by Imaginous, who I thank for this great way of shortening my day to day trip to work. :)

**Comment by Imaginous** [comment]
You can always try to increase the value a bit more. 
Also check if the belt is not too tight.

If the issue remains simply reach out to Cowboy.

**Comment by OpenAai** [comment]
> 

What value exactly? The juddering is between 30-32 km/h, so I don’t think support will be happy to help me ;)

**Comment by Imaginous** [comment]
It's not value for the start rotation count.

You can try a different value for the field weakening.
And stil check the tension of the belt.

**Comment by OpenAai** [comment]
Thanks again. I’ll let you know the outcome of the changes, ie FW 20 and looser belt

**Comment by OpenAai** [comment]
I loosened the belt and changed field weakening to 10, which did the trick, the tremor in the bike is almost gone gone. The noisy engine is the last thing, but that’s probably for support. 
Thanks again for your support!

**Comment by Imaginous** [comment]
Great to hear, I will close this issue.

Is the noise really the engine or the free wheel when you stop pedaling.
Because the free wheel is noisy on a C3.
