### ISSUE TITLE
Calculation not correct?

### ISSUE THREAD

**Issue by salzheld** [Imaginous/Cowboy_Untamed#2]
Using your new Profiles is fantastic.

Leaving speed ranges empty gives 100% support. But adding 100 gives not the same support. Actually feels like 50%.

I am using a Cowboy 2.

In the 1 Profile I added support only < 20 kmh. This way my battery lasts WAY longer than before. Really great addition.

**Comment by Imaginous** [comment]
I did some testing, the values in the registers for the "Maximum Power" are the same when I only read them, with the values when I wrote 100% (4096 RAW). I can't imagine these values are different on a V2, since the values are a percentage.

The value for "Peddle Max Torque" could be different. This value is not a percentage. I just used the value of the V1 as maximum value. Since the V1 to V3 use the same torque sensor I also can't imagine they are different, but it's more likely.

There for I want to ask you if you can read out value "Throttle Full Voltage" on the expert settings page.

**Comment by salzheld** [comment]
2.05 Volt

**Comment by Imaginous** [comment]
@salzheld you said that it felt more like 50% power.
Was this with the "Peddle Torque Max" value set to 100?

I see a difference between the versions of the bikes here. The default voltage for the V1+ is 3.69 volts.

Please let me know when it felt weaker that you had set the "Peddle Torque Max" value.

**Comment by salzheld** [comment]
100 weaker
without strong as normal
100 = 3.7 V
50 = 7.36 V
without = 2.05 V

Don't know if I do it correct, as less support results in higher voltages.

**Comment by Imaginous** [comment]
@salzheld You did it correct, higher values give less support.

This also confirms my idea of the problem. I will alter the code so it will first fetch the value from the motor controller and then will make the correction.

This will introduce a new problem, if start a preset twice the value will be incorrect. This can be overcome if I know the original RAW value.

So if you would like to read the voltage one more time but give me the RAW value. I can then enter this value in the system and verify against it.

**Comment by salzheld** [comment]
2.05 V
8397 RAW

**Comment by Imaginous** [comment]
@salzheld I will try to make a fix tomorrow.
It will fetch the value from the bike. 
If it's a known value it will apply the percentage chosen, otherwise I will ignore the setting.

I think that's the safest route.

**Comment by Imaginous** [comment]
@salzheld I fixed the bug by storing the default value when the "Quick Launch Presets" main screen is opened the first time.

For you it's important to:
- Lock your bike
- Upgrade the Cowboy Untamed app
- Connect to your bike
- Go to "Quick Launch Settings"

If you want to keep your current "Peddle Max Torque" value the same you have to devide it by 1.8. So for example 80% would become 80/1.8 = 44. This should give you about the same value as before.

You can [download V3.05 here](https://github.com/Imaginous/Cowboy_Untamed/releases/download/V3.05/cowboyuntamed_v3_05.apk) to fix the problem.

**Comment by salzheld** [comment]
Thanks, will check and test the new version. Did a first ride to work without problems but was using my fast preset (maximum performance).

Really glad you made this wonderful app. An eco-mode is definitly missing in the official app. I am looking forward for long tours in the summer now.
