### ISSUE TITLE
Error setting preset

### ISSUE THREAD

**Issue by diogodh** [Imaginous/Cowboy_Untamed#20]
Hello. I am using tasker and NFC tag to unlock my bike. In the last beta version, when triggering the unlock default profile, the normal, it shows the following error as a toast message "Error setting preset: Cannot invoke setValue on a background thread".

Any idea on how to fix it?

**Comment by Imaginous** [comment]
I will try to have a look at it tomorrow.

Something that must have gone rogue in the latest beta.

**Comment by Imaginous** [comment]
I just tested this task with version V3.51 beta.
![Screenshot_20220605-223051](https://user-images.githubusercontent.com/68418842/172069407-3985dd39-1bb5-4bab-90a5-05a5f28fade6.png)

I didn't get any errors... what does your Tasker task look like?

Maybe give V3.51 a try.

**Comment by diogodh** [comment]
![Screenshot_20220605-214743](https://user-images.githubusercontent.com/18470550/172069934-3b0b9a44-435a-408a-b5a7-9da09e24a56f.png)
![Screenshot_20220605-214748](https://user-images.githubusercontent.com/18470550/172069937-4fff21be-e1ac-41b5-af52-5edeef6f917f.png)
![Screenshot_20220605-214753](https://user-images.githubusercontent.com/18470550/172069942-144c9045-6a73-4af1-9213-f2aec3c81534.png)

**Comment by diogodh** [comment]
I will return to 3.22 and re-check if keeps working. Maybe was something with tasker, don't know. Will give you feedback soon

**Comment by Imaginous** [comment]
Did you still got this error with V3.51?
Made some changes in there for my Tizen watch which gave a similar error.
I tested wit V3.51, which didn't gave me errors and the bike unlocked and the preset was applied.

**Comment by diogodh** [comment]
No. I will only be able to test with both version tomorrow.

**Comment by Imaginous** [comment]
If I understand it correctly the second time it works, the first unlock fails?

Does it work if you use the DirectUnlockActivity?
This is for testing. It seems, in your case, it is unable to store the last activated preset in your case.
So by testing the DirectUnlockActivity I can pinpoint the problem a bit better.

For some reason it does not happen on my phone, so it's a bit harder to debug.

**Comment by diogodh** [comment]
Going a few days in holidays but will give you more feedback as soon as I
can with the settings you said me.
If you want any specific debug log just say.
Thank you!

**Comment by Imaginous** [comment]
I have made some minor changes for you, you may give this beta V3.52 a try.

If you can give me a debug log, if it's still not working, that would be great.

[cowboyuntamed_v3_52_Beta.zip](https://github.com/Imaginous/Cowboy_Untamed/files/8918304/cowboyuntamed_v3_52_Beta.zip)

**Comment by ThyMaster34** [comment]
Same issue here with both versions (3.51 and 3.52.) Reverting to 3.34 and error msg and behaviour is gone. So it seems there is some code regression between 3.34 and 3.5+

**Comment by Imaginous** [comment]
What was the exact toast message in V3.52?  - I changed some text to pin point a more specific location.

To debug you have to connect the ADB debugger software via USB to your phone to capture a log.

**Comment by ThyMaster34** [comment]
Just for the records:

> If I understand it correctly the second time it works, the first unlock fails?
_Yes, correct!_
 
> Does it work if you use the DirectUnlockActivity? This is for testing. It seems, in your case, it is unable to store the last activated preset in your case. So by testing the DirectUnlockActivity I can pinpoint the problem a bit better.
_Yes, it does work in the main app using the connect slider straight away_

The answers go for both 3.5x versions

**Comment by Imaginous** [comment]
Something got really fishy with the addition of the dashboard.
I have to rework a bit of code to get it correct again.

Working on it, keep you all informed.

**Comment by diogodh** [comment]
I asked only because of this bug. What would be the most fail proof option
to choose :)
Thank you

**Comment by Imaginous** [comment]
Both should work now, so if you don't mind... test both ;)

**Comment by Imaginous** [comment]
Thank you all for testing... case closed ;)
