### ISSUE TITLE
C4ST field weakening

### ISSUE THREAD

**Issue by ceraz68** [Imaginous/Cowboy_Untamed#21]
Now that C4 and C4ST are sold on the US market, I assume they are not speed limited like in the EU.

If so would it make sense to find someone in the US to tell us the Cowboy default  setting for the field weakening values?

**Comment by ceraz68** [comment]
Sorry I wasn't clear enough, I'm in the EU using untamed ;-)

I was thinking that there may be merit to read the settings of a US model as these would have been internally validated by Cowboy to allow the bike drive up to 20mph (32kmh).

**Comment by Imaginous** [comment]
I own a C1+ which still has the "off road" mode.

The only thing which is different is the set maximum speed.

So it's very likely the US version has only a higher speed limit.
So Untamed will just work the same on US versions.

**Comment by ceraz68** [comment]
Thanks for your answers and time ... great support to the Cowboy community :-)
