### ISSUE TITLE
add ability to switch off GSM/GPS telemetry

### ISSUE THREAD

**Issue by whereistom** [Imaginous/Cowboy_Untamed#23]
For battery longevity and privacy.

Cowboy data collection and sharing is not friendly to its customers.

**Comment by Imaginous** [comment]
I have not seen an option to do this in the original code. 

Without physically removing the SIM card.

**Comment by whereistom** [comment]
How hard is it to remove the SIM and does the bike function normally if removed?

**Comment by Imaginous** [comment]
On a C1 it's underneath the plastic lit in the top tube which can be easily opened.

On other models it's a bit trickier, the plastic lit will often break.

The simcard is inserted in a sim slot so easy to remove.

The bike will still be functional.

**Comment by Imaginous** [comment]
For security reasons I have hidden my previous answer.

I haven't found a software way to do this.
So I will close this issue.
