### ISSUE TITLE
Bug in the app

### ISSUE THREAD

**Issue by diogodh** [Imaginous/Cowboy_Untamed#26]
In the expert functions, inside 0010 now you now have two 0027 instead of one 0027 and one 0029.
I was trying to follow the tutorial for auto unlock with key and notice the 0029 disappeared.
![Screenshot_20220929-190358](https://user-images.githubusercontent.com/18470550/193109406-43574e7c-891b-487b-affd-7f0cef0238ca.png)

**Comment by Imaginous** [comment]
I have altered the code, it will be fixed in the next version (V3.57).

No time to publish right now ;)

**Comment by diogodh** [comment]
Thanks.  Is still possible to write the values on the board to make auto unlock with key work in this version someway or do I need to wait to the next one (or revert to an older version)

**Comment by Imaginous** [comment]
You can enter the values manually.
Select 0010 and enter address 29, then press READ, the RAW value should show the current number of seconds.
In the raw value field you can enter the new number of seconds and then press WRITE.

**Comment by diogodh** [comment]
It's still possible to enable the auto unlock the bike with key on C2 with
this version?

**Comment by Imaginous** [comment]
I don't know if the C2 supports it.
It has to be in the firmware of the bike. I haven't changed anything. If it worked it should still work.

I have a C1 one, there it doesn't work because it's not supported in the bike's firmware.

**Comment by diogodh** [comment]
It does support cause in older versions it worked. The only thing is that as it has two 0027 instead of 1 0027 and 1 0029, it don't allow to manually select the 0029
