### ISSUE TITLE
Pixel Watch Installation error

### ISSUE THREAD

**Issue by salzheld** [Imaginous/Cowboy_Untamed#29]
Performing the installation is not possible: adb install cowboyuntamed_watch_v1_00.apk

Error: 
Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Reconciliation failed...: Reconcile failed: Package nl.imaginous.freecowboy requires unavailable shared library com.google.android.wearable; failing!]

And to connect to wifi I first had to pair it using the pair command.

**Comment by Imaginous** [comment]
Which version of WearOS do you have?
Which watch brand and make?

It seems it's only partially installed. It's missing the shared components.

**Comment by salzheld** [comment]
Sorry, I sorted it out. I had to use the -s command to install it to the pixel-device (via IP). Don't know why but there where to devices connected in adb.

**Comment by Imaginous** [comment]
I have altered the documentation with -s and also added - r.

It may help others.
