### ISSUE TITLE
cowboy app doesn't start

### ISSUE THREAD

**Issue by salzheld** [Imaginous/Cowboy_Untamed#3]
Good idea to start the Cowboy-App after setting a preset.

Sadly, it doesn't work here. 

Using a Cowboy 2.

**Comment by Imaginous** [comment]
Do you get any message?

And I assume you have toggled the switch on the presets screen?

**Comment by Imaginous** [comment]
![sketch-1625168857326](https://user-images.githubusercontent.com/68418842/124181603-03f19880-dab6-11eb-909b-f37ffcb4c07e.png)

**Comment by salzheld** [comment]
no, yes, yes.

**Comment by Imaginous** [comment]
@salzheld which version of the Cowboy app do you have?

I'm trying to figure out why it's not working on your phone.

Are you close to your bike, and does it unlock?
The Cowboy app will only be started if all settings are applied. 

Can you post a screen shot of the preset screen with the preset you are trying to activate?

**Comment by salzheld** [comment]
Version: 2.11.6
Bike unlocks perfectly
Profile is applied (with tooltip mesage)

Will post an image later.

**Comment by Imaginous** [comment]
@salzheld I have uploaded [Cowboy Untamed V3.07](https://github.com/Imaginous/Cowboy_Untamed/releases/download/V3.07/cowboyuntamed_v3_07.apk) this includes some extra tooltip messages when starting the original Cowboy app.

- *Could not find Cowboy app.*<br>This indicates for some reason that the *bike.cowboy.com* app could not be found. Are you using any virsus scanner?
- *Could not start Cowboy app: <some message>*<br>Should give some more information about what went wrong.

I have the same version of the Cowboy app. I'm using Android V10 on a Sony.

**Comment by salzheld** [comment]
Message: Could not find...

No Viruskiller installed. Galaxy s10. Near stock.

**Comment by Imaginous** [comment]
@salzheld which version of Android?

I'm trying to find a pattern. The Cowboy app versions are the same, so the package name should also be the same.
Only the Android version might be a problem. Maybe a rights problem?

**Comment by salzheld** [comment]
OneUI 3.1
Android 11
Don't know the pakage name.

**Comment by Imaginous** [comment]
@salzheld I made some changes to the installation package. 
It now includes `    <queries>
        <package android:name="bike.cowboy.app" />
    </queries>` in the manifest file. This should solve the excuting rights issue on Android 11.
Unfortunately I don't have any Android 11 devices at my disposal. 

Please try [V3.09](https://github.com/Imaginous/Cowboy_Untamed/releases/download/V3.09/cowboyuntamed_v3_09.apk).

**Comment by salzheld** [comment]
It works. Thank you. You are great.

**Comment by Imaginous** [comment]
You're welcome, you are the most supportive tester!
