### ISSUE TITLE
Download link here returns 404

### ISSUE THREAD

**Issue by gzak** [Imaginous/Cowboy_Untamed#30]
Title says it all, the download link in the readme here takes me to the GitHub 404 screen, so I’m not sure where to go to get latest.

**Comment by Imaginous** [comment]
I forgot to update the link when I uploaded V3. 61.
It's fixed now.

You can also use the link below:
[V3.61](https://github.com/Imaginous/Cowboy_Untamed/releases/download/V3.61/cowboyuntamed_v3_61.apk)
