### ISSUE TITLE
Headlight

### ISSUE THREAD

**Issue by Jaaap** [Imaginous/Cowboy_Untamed#32]
Assuming i know **nothing** about 3D-printing, would it still be possible to get your much improved headlight onto my Cowboy 3?
Any advise appreciated.

**Comment by Imaginous** [comment]
I'm not 100% sure if the headlight cover of the C3 is exactly the same as the C1.

Anyone with a multi material printer should be able to print it.
I don't sell or print them. The printing is up to you.

**Comment by Jaaap** [comment]
Ok thank you.
