### ISSUE TITLE
error in latest version when using presets

### ISSUE THREAD

**Issue by sozifa** [Imaginous/Cowboy_Untamed#33]
With the latest version activating a preset always returns an error - Android 13 - reverted to latest 2022 version and everything is working fine again

**Comment by Imaginous** [comment]
What error do you get?

Can you post a screenshot?

Which phone model?

On my Zenfone 9 with Android 13 and in the emulator I don't get an error. I need a bit more information.

**Comment by sozifa** [comment]
Good Morning,
I just reinstalled the latest version to take a screenshot of the error code and now it just works - strange but  maybe with the first installation domething just went wrong - issue closed -  sorry for any inconvenience caused
