### ISSUE TITLE
Bike losing battery connection 

### ISSUE THREAD

**Issue by bbrgx** [Imaginous/Cowboy_Untamed#34]
Hi,

I'm struggling with my untamed C3 constantly losing connection to the battery. After riding for just a few hundred meters, the bike will turn off and show the no battery sign on the app. Then it will connect again, tapping on the top of the battery usually helps. But then it loses connection again... and so on.

I have already changed the connectors on the bike and added a new spacer, but nothing changed. Could that be the battery itself? Does the untamed app have anything to do with it?

Really appreciate your help.

**Comment by Imaginous** [comment]
It has nothing to do with Untamed.
You say when you tap the battery it works again.

I know a case where the was a cable breach inside the battery on the data pins. Those are the small pins.

Since you replaced the connector and added a spacer it is most likely it's in the battery itself.

Untamed only changes 2 registers in the motor controller according to ASI specs (manufacturer of the controller).

**Comment by bbrgx** [comment]
Thanks for your reply.

Do you know if there is a way to fix the data pins without changing the battery?

Unfortunately, Cowboy is denying any support due to the software alteration.

**Comment by Imaginous** [comment]
It's fixable, but not for the faint hearted.

But just point out there is no logical standpoint that the battery data connector failed because of a speed upgrade.

Apply some pressure

**Comment by bbrgx** [comment]
Ok. Do you mean that it would be possible to open the battery and change the data pins? Are they a piece that can be found on the market or can they only be found through Cowboy? 

I am applying a lot of pressure with Cowboy, but they are extremely uncooperative. And general e-bike repair shops have no clue :(

**Comment by Imaginous** [comment]
You can open up the battery (Niels on the Facebook group did it a couple of times). Then resolder the wires to the data pins.

**Comment by bbrgx** [comment]
Alright, I'll try that. Thanks again.

**Comment by bbrgx** [comment]
Hi,
I'm reopening this thread to ask if you need any spare parts to do this kind of repair, or if it's possible to just fix the data pins with a solder and nothing more? 
I am asking this because I have contacted several repair shops but nobody seems to be keen to do this repair, they all say that they don't have spare parts for Cowboy bikes and therefore they cannot do it. 
Not having experience with a solder myself, I'm trying to find a place that can do this kind of job. 
Thanks for your help.

**Comment by Imaginous** [comment]
Do you have a spacer installed on your Cowboy between the battery connector?

If not order one at Cowboy.
As said earlier maybe Niels Vaesen or Brook Waters on the Facebook Cowboy (BE-NL) is willing to help you.

I don't know anyone besides them who might want to fix it.

**Comment by bbrgx** [comment]
Yes, I do have a spacer installed. I have been doing all possible repairs on the bike through Cowboy assistance, but that was not the issue. When I ride with a different battery everything goes fine, so it must be a battery issue. 

I will try to reach out to Niels and Brook directly, thanks again.
