### ISSUE TITLE
Can't scroll on Xperia V

### ISSUE THREAD

**Issue by x5nder** [Imaginous/Cowboy_Untamed#4]
Weird behavior: I found my old Xperia V and decided to use it for Cowboy Untamed, but after installing and running your app, I can't scroll on the main screen (so all I can set is the field weakening and I can see half of the auto-unlock setting). Any ideas? :x

**Comment by Imaginous** [comment]
I will check the code. I assume there is no scroll control. Therefore you can't scroll.

What is the screen size and resolution of the phone. Then I can test with those sizes in the emulator.

**Comment by x5nder** [comment]
Ahh, that would explain why. Yeah, it's quite an oldie, but it's the only Android device I have in my home.
Xperia V = 4.3" 720x1280 (342ppi)

**Comment by Imaginous** [comment]
As a workaround you could set the font (display) size back to "normal". This should fit.

I think you are using large fonts.

**Comment by x5nder** [comment]
No, but... that gave me an idea. Set the font size and display size to 'small' instead of 'default' and now I can actually see all Untamed elements, so that works for me as a solution! Dank je ;)

**Comment by Imaginous** [comment]
Great that you solved it. Due to my perfectionism I will still try to fix it.

Hope to create an update tonight.

**Comment by x5nder** [comment]
In that case, I did some quick testing for you--
Decreasing the font size from 'default' to 'small' doesn't really solve the issue
Decreasing the display size from 'default' to 'small' is enough to solve the issue (font size can stay at normal) 

Font size = Default
Display = Default
![font_normal_display_normal](https://user-images.githubusercontent.com/4243542/127024652-9c558cc8-d49d-4548-9265-6607b9332a38.jpeg)

Font size = Small
Display = Default
![font_small_display_normal](https://user-images.githubusercontent.com/4243542/127024645-44a6e134-8208-4aac-8c0d-f785ce9d7a8c.jpeg)

Font size = Default
Display = Small
![font_normal_display_small](https://user-images.githubusercontent.com/4243542/127024621-76966ac5-4809-49db-9b8a-eab4e58715f1.jpeg)

Font size = Small
Display = Small
![font_small_display_small](https://user-images.githubusercontent.com/4243542/127024639-8ec295c3-1486-4a1f-89f2-014e12037f9a.jpeg)

**Comment by Imaginous** [comment]
I have uploaded [version V3.11](https://github.com/Imaginous/Cowboy_Untamed/releases/download/V3.11/cowboyuntamed_v3_11.apk) in which you should be able to scroll all controls into view.

Please let me know if it works out.

**Comment by x5nder** [comment]
Works! :)
