### ISSUE TITLE
new adaptive power firmware

### ISSUE THREAD

**Issue by tsbalpha** [Imaginous/Cowboy_Untamed#40]
first of all amazing work here man.

i have a request wich might help alot of people like me that dont want adaptive power and just want all the power all the time. as of the new update adaptive power cant be turned off in the official app so maybe you could switch it on and off with the esp? i dont think cowboy completely removed it from the firmware of the bike so in theory it should be possible to acces it with your amazing app. 

anyways thanks for taking the time to make this app and reading my request.

**Comment by Imaginous** [comment]
I own a Cowboy C1+, this one hasn't got adaptive power.

So I don't know which register I should "hack".
It's also possible that the firmware in the main controller actively steers the motor controller.

I don't know how they handle it and don't have a bike to tinker with.
