### ISSUE TITLE
Compatibility with Firmware 4.21.0

### ISSUE THREAD

**Issue by hg8** [Imaginous/Cowboy_Untamed#41]
Hey 👋

First of all I know you don't own a C4, I am creating this issue to see if there is a possibility of collaboration with the community to debug and test fix for this problem.

--

Firmware **4.21.0** ("AdaptivePower 2.0") included a lot of changes, for example it's the first time in 2 years that an update reverted my Untamed settings. 

Once setting again "_Torque (no speed limit) + Field weakening_" in the app the bike mostly works fine and behaves as expected, **expect** that the engine completely shut off when starting from a stopped position (It kind of feels like engine protection or something ?). The bike is still on but the engine won't work at all until you re-lock and unlock the bike (doesn't even work every time).
When reverting to "_Torque and speed limit_" from the Untamed app, the problem fully disappears. 

I tried various field weakening settings but none changed the issue. Any idea on how to debug this issue or what could be the cause ?

Thanks!

EDIT: Or alternatively, if anyone knows a way to revert to a previous firmware version ?

**Comment by Imaginous** [comment]
It feeds my "fears", I believe they are controlling the motor controller more directly via the main PCB.

I assume they adjust the torque sensor dynamically.
I don't quite get it why only setting torque without speedlimit dusturbs the power output. Field weakening can do this.
It's also possible the changed register addresses, so we are  changing wrong addresses.

**Comment by ezly123** [comment]
I'd like to report I have the exact same issue, C4 with AP 2.0 and Untamed.

**Comment by BrianMnairB** [comment]
Yeah, same 'issue' here. I tried to go back to default settings and only unlock the speed limit. So without field weakening, just to see if I'll run into the issue again and also to see if the field weakening is correctly reverted back to default (0).

**Comment by hg8** [comment]
> I assume they adjust the torque sensor dynamically.

Indeed, seems like it and it would explain why it sometimes works sometimes doesn't.

> It's also possible the changed register addresses, so we are changing wrong addresses.

Could we use expert mode to read address values since the latest update? Would that help make sense of what is happening ?

**Comment by BrianMnairB** [comment]
The version is v4.21 btw, not v4.12

**Comment by Imaginous** [comment]
> > I assume they adjust the torque sensor dynamically.
> 
> Indeed, seems like it and it would explain why it sometimes works sometimes doesn't.
> 
> > It's also possible the changed register addresses, so we are changing wrong addresses.
> 
> Could we use expert mode to read address values since the latest update? Would that help make sense of what is happening ?

You can read every address, only it is going to be trail and error.
Also there is no easy tool to compare all changes at once.
At this moment I also have some health issues which prevent me from investing a lot of time/work into this project.

Also the NDA is still in effect, so I can't share the source without any legal issues.

**Comment by hg8** [comment]
Ah, I am sorry to hear that.
It's all good, take all the time you need and take care of yourself first 👍  It's already amazing all the work you've put in for the cowboy community. Thanks a lot for that.

**Comment by Cryptosaurus89** [comment]
Hope you'll be well soon!

I have the same issues with 4.21 version. Is it possible to downgrade?

**Comment by maakle** [comment]
I also share the same problem. I have a C4 Classic on Firmware v4.21.0. But I am unable to perform the second update 2/2 for the engine. It always stops with an error message during the update.

What I tried now was to use the Untamed App to reset to default settings. This somewhat works, it threw sometimes an error as seen on the images below but in the end worked that the bike has now again the speed lock and is back to how it was before. 

`fieldweakening: Operation failed: 010300810001D422`
`motormode: Operation failed: 0103000B0001F5C8`


Nevertheless I am still unable to perform the second update for Adaptive Power 2.0. Which leaves me now basically with a broken bike on Firmware v4.21.0 where the engine shuts off from time to time during the ride...

Any other ideas how to I fix this? 
Is there another way that I can reset the engine to factory settings? And then at least perform the Adaptive Power 2.0 2/2 update? Or did Cowboy somehow block this now
Is there a way of going back to Firmware v4.19.0 where everything was working?

![IMG_2946](https://github.com/user-attachments/assets/9887f2c7-b9b0-4b63-9220-625c88b49125)
![IMG_2945](https://github.com/user-attachments/assets/b0876695-0d71-472d-b83c-aacbff81348b)

**Comment by Imaginous** [comment]
When you connect and field weakening is empty and torque and speed limit is selected. Everything is default.

Unless you used the expert settings and or presets and stored these in firmware.

**Comment by maakle** [comment]
I double checked with the iOS App from the Unleashed project that everything is fully reset and back to defaults.

But still no luck in updating to Adaptive Power 2.0. It'll show me the error screen attached. Sorry for the German but it basically says "The update failed, please try again later."

Which leaves us right now with 2 options:

1. Cowboy can someone fix this and allow upgrading to the second update -> I booked an appointment with one of their mechanics. Maybe they can perform some black magic 
2. @Imaginous can find a way of making Untamed work with v4.21.0 is there any further way we can help or assist you?

Or is anyone else able to perform both updates? On Reddit some people claimed that.

![image](https://github.com/user-attachments/assets/a363c582-5ae8-47eb-8bca-2540e5527885)

**Comment by hg8** [comment]
> Or is anyone else able to perform both updates? On Reddit some people claimed that.

I was able to perform both updates without issues, while untamed settings applied. 

May be silly but have you tried to uninstall and reinstall the cowboy app? I had update issues in the past and reinstalling the app and relink the bike always worked. 

Maybe try to install the cowboy app on a different phone as well? I think your update issue is not linked to Untamed.

**Comment by maakle** [comment]
So I tried what you suggested @hg8 this morning. (I deleted and installed the Cowboy App again, removed the bike and connected it again etc.) It was unfortunately not successful and the second update still doesn't finish. I'll try to see if Cowboy can fix this and help me to finish the second update. But this seems unrelated to Untamed for sure. There is a Cowboy store very close by work location, maybe I can ask them there. 

That being said, my bike is now technically back in default settings with speed limit and no field weakening and it still turned off this morning 1x during my morning commute. So perhaps Firmware v4.21.0 introduced something that is causing this. No matter if Untamed is being used or default settings from Cowboy.

Btw I also experienced the exact same thing like you @hg8 that when I arrived at work, the bike briefly completely shut of and turned back on then again. That being said, my bike is now on default settings and this still happened.

**Comment by Imaginous** [comment]
I know multiple occasions that the update successfully completed. With and without Untamed.

I also heard that non Untamed riders sometimes have shutdowns with AP2.0 when starting uphill.

So it seems the over current margin is too tight in AP2.0.

@maakle you can try to enable a preset in which you lower the power output for the lowest speed group to 50% or maybe even lower.

And torque without speed limit and the desired field weakening.

Don't store anything in flash, but just use the preset and make some test drives.

Lowering the power might prevent the overcurrent when starting from a standstill.

**Comment by Imaginous** [comment]
At everyone with _Adaptive Power 2.0_ could you try the following:

1. Create a preset. See [Presets](https://github.com/Imaginous/Cowboy_Untamed/blob/main/Presets.md) for more information.
2. Set the desired field weakening (**15** for example)
3. Set the _1. Maximum power 0-100% for 0-5km/h_ to **50**<br>You can play with this value 100% is default (or empty), maybe it has to be lower, maybe it can be higher.
4. Click _STORE PRESET_.
5. Use the preset
6. **NOTE:** Don't use the _FLASH_ button on the main screen while using a preset.

I wonder if the problem of the motor power dropping out is fixed.
If it is fixed I can make an option that this is applied when specifiing you are using _Adaptive Power 2.0_.
If it only works for one start / stop, but when you start from a standstill again and it fails again it might be unfixable.
![125077364-512ac700-e0c1-11eb-9a87-b3722a61099e](https://github.com/user-attachments/assets/aeb31ec6-60c1-4a95-a8bd-5e7506c8e42f)<br>
![](https://user-images.githubusercontent.com/68418842/121254592-badd6880-c8aa-11eb-86db-a6b5ab1bea7f.png)

**Comment by BrianMnairB** [comment]
Not sure if this is useful info, but Cowboy pushed the same upgrade again (I think a wild attempt to easy fix the motor failure on stop/start). Result: issue not solved, but when I opened Untamed it showed the old field weakening %, not the one after setting it on 0 before the upgrade. I changed it to 0 when the problems started a few weeks ago. I even read the values a few times from the bike and it confirmed it was set to 0. After the upgrade from Cowboy the speed limit was active again, but strange thing was the field weakening showed my old 18% (greyed out, but still...). Any ideas why or how this is possible?

**Comment by Imaginous** [comment]
> Not sure if this is useful info, but Cowboy pushed the same upgrade again (I think a wild attempt to easy fix the motor failure on stop/start). Result: issue not solved, but when I opened Untamed it showed the old field weakening %, not the one after setting it on 0 before the upgrade. I changed it to 0 when the problems started a few weeks ago. I even read the values a few times from the bike and it confirmed it was set to 0. After the upgrade from Cowboy the speed limit was active again, but strange thing was the field weakening showed my old 18% (greyed out, but still...). Any ideas why or how this is possible?

It sounds like the field weakening was not reset (but then it should not be read back), or Cowboy copy all motor settings to their servers and for some reason push them back after an update.

But try to disable them, or try the preset. When activating a preset the motor settings are overwritten with the filled in values.

**Comment by maakle** [comment]
> Not sure if this is useful info, but Cowboy pushed the same upgrade again (I think a wild attempt to easy fix the motor failure on stop/start). Result: issue not solved, but when I opened Untamed it showed the old field weakening %, not the one after setting it on 0 before the upgrade. I changed it to 0 when the problems started a few weeks ago. I even read the values a few times from the bike and it confirmed it was set to 0. After the upgrade from Cowboy the speed limit was active again, but strange thing was the field weakening showed my old 18% (greyed out, but still...). Any ideas why or how this is possible?

Also new update from my end:

Last week Cowboy shipped an update to my bike or did some black magic in the background. I was chatting with customer support and suddenly I was able to upgrade to AP2.0 with the 2/2 engine update.

That being said the start/stop problems didn't disappear, neither the mid ride engine shut off. Everything started after me upgrading from 4.19... so anyone who has the chance, stay in that!

My latest development is now even that the engine doesn't work at all anymore. I am able to unlock and start the bike via the Cowboy App, but the engine doesn't kick in anymore or give me any support, turning my bike useless...

I don't know in what capacity that is now related to Untamed since there are people using v4.21, AP2.0 and Untamed though right? @Imaginous

**Comment by Imaginous** [comment]
Some are using it, but everyone has shutdowns when high torque input is given. In this case the safety of the motor controller kicks in.

But did you have Untamed enabled during your problems?
I also heard non Untamed riders have issues with shuttingdown motor controllers after the update.

**Comment by maakle** [comment]
@Imaginous so for the moment I turned everything back to default values when performing AP2.0 update. Hence I'm not using Untamed at all anymore. Though my C4 is useless now at this point. Don't know if it would magically work again if I use Untamed lol

**Comment by Imaginous** [comment]
I'm afraid Untamed isn't the culprit. Check all cables and check if the bit entering the motor is still okay.

**Comment by BrianMnairB** [comment]
And after weeks of 'investigation' they play the out of warranty card...
So safety shutdown of the motor is causing this, what @Imaginous already suspected.
I'm not sure what they mean by 'unable to calibrate the controller' though.

![Screenshot_2024-09-10-10-05-23-709_bike cowboy app](https://github.com/user-attachments/assets/bec07a73-fe03-448d-9d58-b1ec187303f2)
![Screenshot_2024-09-10-10-05-28-503_bike cowboy app](https://github.com/user-attachments/assets/3693caa1-5a83-4ae0-aaa4-5a2ba0e5ab18)

**Comment by Imaginous** [comment]
Unfortunate to hear, I know users without Untamed having same sort of issues with adaptive power 2.0. 

One of them has a beta Cowboy firmware which seems to resolve the issues.

**Comment by BrianMnairB** [comment]
Update: Firmware 4.21.3 solved the issue for me. It makes me sick Cowboy is using the no warranty instead of admitting it is a software bug in their firmware. Thanks for pointing out there was a new firmware. Hopes this solves the issue for many riders 🤠

**Comment by hg8** [comment]
@BrianMnairB How did you get the update ? I've been on the Beta since forever and no update from 4.21.0 so far 😮‍💨

**Comment by BrianMnairB** [comment]
> @BrianMnairB How did you get the update ? I've been on the Beta since forever and no update from 4.21.0 so far 😮‍💨

@hg8 Not sure, but I assume it was part of the research/solution by the R&D department.
I know they can push firmware to specific users. I think they are still testing this version (because now I have bluetooth connection issues).

**Comment by Psanchini24** [comment]
I have a C4 classic (more than 2 years old - no warranty) .Just before warranty expired back in April  24 the engine would stop responding midway (no assist and everything else in the app was working). Cowboy advised the official local bike shop to lower the belt tension to the lowest levels to fix it. The issue description seemed similar hence my feedback.

I wanted to install Untamed now that I am out of warranty but... Will it work since I am on V4.19.12 (looking at all the discussions above?)

**Comment by Imaginous** [comment]
It might work, the latest (beta) firmware from Cowboy works again with Untamed and Adaptive Power 2.0.

**Comment by hg8** [comment]
![image](https://github.com/user-attachments/assets/e7309de3-3815-4a80-bb91-baed5e388d37)

Finally received the latest update (4.21.5). It improves the situation but doesn't 100% fix it as the engine lock still happens from time to time. Closing this issue for now since it's not really related to Untamed itself. 

However I still think it would be great to have a way to backup and restore previous firmware versions. If anyone has an idea on how to do so, please reach out!

**Comment by Imaginous** [comment]
You can try using a preset and using a reduced power setting for the lowest speeds. Let's say 40, 50, 60, 70% for the speeds upto 10km/h.
