### ISSUE TITLE
No connection to bike after update to Android 12

### ISSUE THREAD

**Issue by sozifa** [Imaginous/Cowboy_Untamed#7]
After the update to Android 12 yesterday, the up doesn't find my bike anymore - I'm on the new cowboy app as well but it worked before Android 12 in that setup -, Bronco does connect,  so does the cowboy app - just Untamed can't pair -  tried to uninstall and reinstall but still same issue..

**Comment by Imaginous** [comment]
I have added the maxSdkVersion = 30 tag.
Please try the attached version. If it doesn't work I have to rewrite the discovery routine.

Please unzip it first.

[Untamed_Test_V3.14.apk.zip](https://github.com/Imaginous/Cowboy_Untamed/files/7383260/Untamed_Test_V3.14.apk.zip)

**Comment by sozifa** [comment]
Thanks for you fast reply -  will have to rest it later as the battery is on the charger right now and it's pouring down outside ;-)  I'll report back ASAP

**Comment by Imaginous** [comment]
You don't have to go outside... if you update the app the bike should be shown in the list. The 'no bikes found' message should be gone.

If not... I have to redo some code.

**Comment by sozifa** [comment]
Just tested it -  no bikes show up and a toast appears saying no paired bikes found - even tested close to the bike with battery attached

**Comment by sozifa** [comment]
Many thanks, happy to test

**Comment by Imaginous** [comment]
I did another minor rewrite (in the hope I don't have to do the larger rewrite yet).
So you may try again ;)

[cowboyuntamed_v3_14_beta.zip](https://github.com/Imaginous/Cowboy_Untamed/files/7390291/cowboyuntamed_v3_14_beta.zip)

**Comment by sozifa** [comment]
Sorry for the hassle and many thanks for your efforts its really appreciated

**Comment by sozifa** [comment]
Yes and already sent you 3 files to that address ;-)

**Comment by sozifa** [comment]
Yes got your emails -  tried once again with a link a few seconds ago to both of them
