### ISSUE TITLE
Unlock Bike when unplug/replug the battery

### ISSUE THREAD

**Issue by CBGTI** [Imaginous/Cowboy_Untamed#8]
Apparently, with Cowboy V3, it's possible to Unlock the bike without using the phone :
You just have to unplug and re-plug the battery within 5sec.
It's a very useful function.
By default, it's unavailable on V1 and V2.
Is it possible ton implement it in your App for all the version of the Bike ?

Thanks for your hard work!

**Comment by Imaginous** [comment]
I did some research on the new Cowboy V3.0.0 app.
I found the following: `MANUAL_UNLOCK_27(27)`

It seems like it has been moved to a different address 27 (int).

If you have a V2/V3 you can try the following:

1. Open Cowboy Untamed
2. Connect to your bike
3. Go to the *Show expert functions* menu
4. Click *GO*
5. Select *0010: Cowboy PCB* on  the first row
6. Select *????: Custom address (int)* on the second row
7. Enter *27* in the *Addr* field
7. Press *READ*, and note the *RAW* and *Value* value.<br>If you get a value of 0 then it's disabled.<br>If you get an error message it's not supported.<br>If you get another value it's enabled.
8. If it's 0 without an error enter *RAW* 20. (You have to remove and re-insert the battery within 20 seconds to unlock the bike).
9. Press *WRITE* (you **don't need to** press *FLASH* on the main screen).

Now it should be enabled if it's supported on a V2. Set the *RAW* value back to 0 to disable it.

**Comment by salzheld** [comment]
Just checked that here with my Cowboy2. IT WORK'S. You are fantastic.

**Comment by diogodh** [comment]
> Just checked that here with my Cowboy2. IT WORK'S. You are fantastic.

That sounds horrible for cowboy brand that states it is a firmware incompatibility. It looses trust on the consumers.
Will you implement that in an app easy toggle dev?

**Comment by CBGTI** [comment]
Amazing! 
Good job! :-)
Thanks a Lot !

**Comment by Imaginous** [comment]
I will upload a new version next week with the corrections in the app.

Enjoy the feature.
