### ISSUE TITLE
Watch app

### ISSUE THREAD

**Issue by sozifa** [Imaginous/Cowboy_Untamed#9]
Have you had a thought about a watch app -  would be so cool if I just can choose a quick setting on the watch (Wear OS3) and that triggers the phone app to send it to the cowboy just like the quick settings companion app on the phone ;-)
Would never need to take the phone out again ;-) 
Happy to do the testing

**Comment by Imaginous** [comment]
Offcourse I thought about that... if I'm gonna make one it will be a Wear OS app. 

At the moment I use a contraption of TaskS2 and Tasker on my Tizen based watch.

I'm sure there must be an Wear OS app that can launch Tasker tasks... if there is such a thing you can already create the functions you like.

My first hit was [WearTasker](https://play.google.com/store/apps/details?id=com.cuberob.weartasker&hl=en&gl=US), this might bring a fast solution to your "problem".

**Comment by sozifa** [comment]
Many thanks will give that a try and report

**Comment by sozifa** [comment]
OK worked so far as I can choose the last used preset -  any idea how to trigger the 3 presets directly with tasker?  -  only downside is two more apps on the phone that are running in the background -  tasker and wear tasker -  but works on Galaxy Watch 4 with Wear OS 3 and Android 12 on the phone :-)

**Comment by Imaginous** [comment]
You can start the following activities from tasker (long press the app in Tasker) to get what you want:
- PresetSlowActivity
- PresetNormalActivity
- PresetFastActivity

**Comment by sozifa** [comment]
Oh,  missed that feature.. Many thanks again -  that's really cool

**Comment by Imaginous** [comment]
Glad I could help out.

I will close this issue for now, I'll note it as a feature.

**Comment by CBGTI** [comment]
Actually, is it any way to unlock the bike with a WearOS watch?

**Comment by Imaginous** [comment]
You can do it with Tasker (paid app) and the app mentioned above.

Just Google for more details on Tasker. You can do a lot with it.
